### PR TITLE
#166789862: Deploy base application to Heroku

### PR DESCRIPTION
**Pull request by manzif**
#### What does this PR do?

 - Deploy base application to Heroku

#### Description of Task to be completed?

- Deploy web application to Heroku to run in the production environment.

#### How should this be manually tested?

- When you open the application on Heroku it shows {"message":"Welcome to the default API route"}.

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- [#166789862](https://www.pivotaltracker.com/story/show/166789862)

#### Screenshots (if appropriate)

- 
image

#### Questions:

- N/A

### CODE REVIEW

**Review by Emile-Nsengimana — COMMENTED** [review]
there are some Hound issues. it would be better if you check on them?

**Review by Dom58 — COMMENTED** [review]
@manzif correct the PR title to respect the rules of PR naming

**Review by adafia — COMMENTED** [review]
Please address the next line issue in your Procfile,

**Review by adafia — APPROVED** [review]

**Review by j4l13n — APPROVED** [review]

**Comment by emukungu** [comment]
@manzif,  Look into the hound issues. Fix them.

**Pull request merged**
