### PR TITLE
#166789890 Users should be able to share the articles

### PR DESCRIPTION
**Pull request by Dom58**
#### What does this PR do?
- create the endpoints to allow users  to share the articles across different channels

#### Description of Task to be completed?
- Users should be able to share the articles across different channels

#### How should this be manually tested?
- First clone it to your machine:
```
https://github.com/andela/ah-lobos-backend.git
```
- Open it using your favorite IDE, I recommend ([vs code](https://code.visualstudio.com/download))

- Install all necessary node modules
```
npm install
```
- Run
```
npm run dev
```
- Use Postman to test out the following endpoints
### API ENDPOINTS
| API | Methods  | Description  |
| ------- | --- | --- |
| `/api/articles/:slug/email-share` | GET | Share article on email |
| `/api/articles/:slug/facebook-share` | GET | Post article on facebook |
| `/articles/:slug/twitter-share` | GET | Post article on twitter|
| `/api/articles/:slug/whatsapp-share` | GET | Share article on WhatsApp |

#### Any background context you want to provide?
- Create `.env` file with the help of `example.env`
- You need to be registered to the system with a valid working email to be able to like/dislike article(s)
#### What are the relevant pivotal tracker stories?
[#166789890](https://www.pivotaltracker.com/story/show/166789890)
##### 1.1 Share article on twitter 
Screen Shot 2019-07-22 at 17 03 28

Screen Shot 2019-07-23 at 16 52 29

##### Tweet with shared link

Screen Shot 2019-07-23 at 16 56 39

##### 1.2 Post article on Facebook

Screen Shot 2019-07-24 at 09 52 27

Screen Shot 2019-07-24 at 09 53 21

##### 1.3 Share article on Email

Screen Shot 2019-07-24 at 09 50 14

Screen Shot 2019-07-24 at 09 51 16
##### 1.4 screenshot of the received email after sharing link

image

##### 1.4 Share article on WhatsApp

Screen Shot 2019-07-24 at 09 47 16

Screen Shot 2019-07-24 at 09 48 54

###### 2. Error if no article found
Screen Shot 2019-07-22 at 17 08 45

###### 3. Mockup
Screen Shot 2019-07-23 at 17 19 06

###### 3.1 when some one click on WhatsApp logo should be able to share article on WhatsApp 
Screen Shot 2019-07-24 at 09 48 54

### CODE REVIEW

**Review by manzif — APPROVED** [review]

**Review by j4l13n — APPROVED** [review]

**Review by Emile-Nsengimana — APPROVED** [review]

**Comment by Emile-Nsengimana** [comment]
please change the like icon on the mockup to reflect the changes that has been made

**Comment by Dom58** [comment]
> please change the like icon on the mockup to reflect the changes that has been made

Done!

**Review by Emile-Nsengimana — APPROVED** [review]

**Review by j4l13n — APPROVED** [review]

**Comment by emukungu** [comment]
why is your email missing the 'To' field?

**Comment by Dom58** [comment]
> why is your email missing the 'To' field?

User himself should fill this field according to his/her choice! Not necessary  to add the default email

**Comment by emukungu** [comment]
add the screen shot of the received email

**Comment by Dom58** [comment]
> add the screen shot of the received email

Done!

**Pull request merged**
