### PR TITLE
#166789884 Users should be able to tag their articles

### PR DESCRIPTION
**Pull request by Dom58**
#### What does this PR do?
- create an endpoint to allow users to tag his article

#### Description of Task to be completed?
- Users should be able to tag their articles
- Create a table which will keep all the tags created

#### How should this be manually tested?
- First clone it to your machine:
```
https://github.com/andela/ah-lobos-backend.git
```
- Open it using your favorite IDE, I recommend ([vs code](https://code.visualstudio.com/download))

- Install all necessary node modules
```
npm install
```
- Run
```
npm run dev
```
- Use Postman to test out the following endpoints
### API ENDPOINTS
| API | Methods  | Description  |
| ------- | --- | --- |
| `/api/articles` | POST | Add a tag to an article |

#### Any background context you want to provide?
- Create `.env` file with the help of `example.env`
- You need to be registered to the system with a valid working email to be able to like/dislike article(s)
#### What are the relevant pivotal tracker stories?
[#166789884](https://www.pivotaltracker.com/story/show/166789884)
##### 1. Adding a tag to created article
Screen Shot 2019-07-19 at 10 01 14

Screen Shot 2019-07-19 at 10 01 35

##### 2. Mockup

Screen Shot 2019-07-19 at 10 20 03

#### Questions:
N/A

### CODE REVIEW

**Review by Emile-Nsengimana — APPROVED** [review]

**Review by adafia — APPROVED** [review]

**Comment by adafia** [comment]
please resolve all outdated hound issues

**Comment by Dom58** [comment]
> please resolve all outdated hound issues

Yes, all of those was fixed

**Review by j4l13n — CHANGES_REQUESTED** [review]
I don't know, how you did it but `codeclimate` can not allow you to have a method with 54 lines. just please try to minimize the `postArticle` method.

**Comment by Dom58** [comment]
> I don't know, how you did it but `codeclimate` can not allow you to have a method with 54 lines. just please try to minimize the `postArticle` method.

Solved before bro from your feature and you know I did that ftom your feedback

**Review by j4l13n — APPROVED** [review]

**Pull request merged**
