### PR TITLE
#166789866 Setup API Documentation using swagger

### PR DESCRIPTION
**Pull request by j4l13n**
#### What does this PR do?

- Setup API Documentation using swagger

#### Description of Task to be completed?

- add swagger-jsdoc and swagger-ui-express packages
- add swaggerDefinition for app title and host
- add options for swagger definition and locate the folder
- add swagger specification for it options
- add comments above the route being documented

#### How should this be manually tested?
- Clone the project
```
> git clone https://github.com/andela/ah-lobos-backend.git
```
- Install all packages
```
> npm install
```
- Run the application
```
> npm run dev
```
- Navigate to `/api-docs`

or check by clicking the following: [link](https://ah-lobos-backend-swagger.herokuapp.com/api-docs/#/)

#### Any background context you want to provide?
- Create `.env` file with the help of `example.env`
- The project structure has been changed

#### What are the relevant pivotal tracker stories?

[#166789866](https://www.pivotaltracker.com/story/show/166789866)

#### Screenshots (if appropriate)

image

Screen Shot 2019-06-30 at 22 05 21

Screen Shot 2019-06-30 at 22 05 36

#### Questions:

- N/A

### CODE REVIEW

**Review by Emile-Nsengimana — APPROVED** [review]

**Review by Dom58 — APPROVED** [review]

**Review by emukungu — CHANGES_REQUESTED** [review]
create a separate folder for the swagger documentation remove it from the routes. 
change the url to reflect the project you are working on.
change the NODE_ENV from test to development in package.json

**Comment by j4l13n** [comment]
> create a separate folder for the swagger documentation remove it from the routes.
> change the url to reflect the project you are working on.
> change the NODE_ENV from test to development in package.json

By removing the NODE_ENV from test to development, do you mean all values that have it?

**Comment by emukungu** [comment]
> > create a separate folder for the swagger documentation remove it from the routes.
> > change the url to reflect the project you are working on.
> > change the NODE_ENV from test to development in package.json
> 
> By removing the NODE_ENV from test to development, do you mean all values that have it?

No, only the package.json file, the application needs to be run in development environment and tests in the test environment. 

In the docs, why did you remove the 400 use case for missing fields?

**Comment by j4l13n** [comment]
> > > create a separate folder for the swagger documentation remove it from the routes.
> > > change the url to reflect the project you are working on.
> > > change the NODE_ENV from test to development in package.json
> > 
> > 
> > By removing the NODE_ENV from test to development, do you mean all values that have it?
> 
> No, only the package.json file, the application needs to be run in development environment and tests in the test environment.

Now this is how my script is: 
```
    "lint": "eslint",
    "test": "NODE_ENV=test npm run create_tables && nyc --reporter=text mocha --require babel-register --require babel-polyfill ./tests/ --exit && npm run drop_tables",
    "coverage": "npm test && nyc report --reporter=text-lcov | coveralls",
    "drop_tables": "sequelize db:migrate:undo:all",
    "create_tables": "sequelize db:migrate",
    "start": "babel-node ./src/index.js",
    "dev": "nodemon --exec babel-node ./src/index.js"
```
Because the NODE_ENV is development by default, I removed the test for drop_tables, create_tables

**Comment by emukungu** [comment]
Could you limit the commit body to a max of 3 entries

**Pull request merged**
